config/routes.rb
Rails.application.routes.draw do
  
  root "users#index"
  resources :users
  resources :spots
  resources :sessions, only: [:new, :create]

  get "/about" => "pages#about"
  
  delete "/logout" => "sessions#destroy", as: :logout

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :spots, dependent: :destroy 
    has_secure_password 
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id 
      redirect_to user_path @user.id 
    else 
      redirect_to new_session_path 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots = Spot.all
  end

  def show
    @spot = Spot.find(params[:id])
    @user = User.find(@spot.user_id)
  end

  def new
    @spot = current_user.spots.new
  end

  def create
    @spot = current_user.spots.new spot_params
    @spot.save
    redirect_to spot_path(@spot.id)
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    @spot.location = params[:spot][:location]
    @spot.descrition = params[:spot][:description]
    @spot.image = params[:spot][:image]
    @spot.obstacles = params[:spot][:obstacles] 
    @spot.save   
    redirect_to("/spots/#{@spot.id}")
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to("/users")
  end

  def authorize_post_view
    @spot = Spot.find(params[:id])
    if @spot.user_id != current_user.id
      redirect_to root_path
    end
  end
  
  private
  def spot_params
    return params.require(:spot).permit(:location, :description, :obstacles, :image, :level_of_difficulty)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new    
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id 
      redirect_to("/users/#{@user.id}")
    else
      flash[:warning] = "Check email and password"
      redirect_to new_user_path
    end 
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.image = params[:user][:image]
    @user.about = params[:user][:about] 
    @user.save   
    flash[:success] = "Your changes have been saved 🤩"
    redirect_to("/users/#{@user.id}")
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to("/")
  end

  private
  def user_params
    return params.require(:user).permit(:name, :email, :password, :image, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/partials/flash' %>
    <%= render '/partials/navbar' %>
    <% if @user && @user.id && current_page?(user_path(@user.id))  %>
      <div class="show-page-container container-fluid">
    <% else %>
      <div class = "container">
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>





  

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
    <div class = "alert alert-<%=key%>">
        <%= value %>
    </div>
<% end %>

app/views/partials/_navbar.html.erb
<ul class="nav justify-content-end">
  <% if logged_in? %>
  <li class="nav-item">
    <%= link_to("Home", root_path, class: "nav-link")%>
  </li>
  <li class="nav-item">
    <%= link_to current_user.name, user_path(current_user.id), class: "nav-link" %>
  </li>
   <li class="nav-item">
      <%= link_to("Edit Profile", edit_user_path(current_user.id), class: "nav-link") %>     
  </li>
  <li class="nav-item">
      <%= link_to("Log Out", logout_path, {method: 'delete', class: "nav-link"}) %>     
  </li>
  <% else %>
  <li class="nav-item">
    <%= link_to("Home", root_path, class: "nav-link")%>
  </li>
  <li class="nav-item">
      <%= link_to("About", "/about", class: "nav-link") %>  
  </li>
  <li class="nav-item">
      <%= link_to("Sign In", new_session_path, class: "nav-link") %>  
  </li>
  <li class="nav-item">
      <%= link_to("Sign Up", new_user_path, class: "nav-link") %>  
  </li>
  <% end %>
</ul>

app/views/spots/create.html.erb
<h1>Spots#create</h1>
<p>Find me in app/views/spots/create.html.erb</p>

app/views/spots/destroy.html.erb
<h1>Spots#destroy</h1>
<p>Find me in app/views/spots/destroy.html.erb</p>

app/views/spots/edit.html.erb
<h1>Edit Spot</h1>
<%= form_for @spot do |f| %>
      <div class="form-group">
        <label>Location</label>
        <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
      </div>
      <div class="form-group">
        <label>Description</label>
        <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
        <small id="emailHelp" class="form-text text-muted"></small>
      </div>
      <div class="form-group">
        <label>Obstacles</label>
        <%= f.text_field :obstacles, class: "form-control", placeholder: "Obstacles" %>
      </div>
      <div class="form-group">
        <label>Level Of Difficulty</label>
        <%= f.text_field :level_of_difficulty, class: "form-control", placeholder: "Level of Difficulty" %>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.text_field :image, class: "form-control", placeholder: "Image URL" %>
      </div>
      <%= f.submit "Edit Spot", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/spots/index.html.erb
<h1> <%= @spot.all %> </h1>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>New Spot</h1>
    <%= form_for @spot do |f| %>
      <div class="form-group">
        <label>Location</label>
        <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
      </div>
      <div class="form-group">
        <label>Description</label>
        <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
        <small id="emailHelp" class="form-text text-muted"></small>
      </div>
      <div class="form-group">
        <label>Obstacles</label>
        <%= f.text_field :obstacles, class: "form-control", placeholder: "Obstacles" %>
      </div>
      <div class="form-group">
        <label>Level Of Difficulty</label>
        <%= f.text_field :level_of_difficulty, class: "form-control", placeholder: "Level of Difficulty" %>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.text_field :image, class: "form-control", placeholder: "Image URL" %>
      </div>
      <%= f.submit "New Spot", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/spots/show.html.erb
<h1>Spot List</h1>

<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= @spot.image %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%=@spot.location%></h5>
    <p class="card-text"><%= @spot.description %></p>
    <ul class="card-text">
      <li><%= @spot.obstacles %></li>
      <li><%= @spot.level_of_difficulty %></li>
    </ul>
    <%= link_to("Destroy Spot", "/spots/#{@spot.id}", {method: 'delete', data: {confirm: "This one...really?"}}) %>  
  </div>
</div>

<!--
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= @spot.image %>" alt="Card image cap">
        <div class="card-body">
        <h5 class="card-title"><%=@spot.location%></h5>
        <p class="card-text"><%= @spot.description %></p>
        <ul class="card-text">
          <li><%= @spot.obstacles %></li>
          <li><%= @spot.level_of_difficulty %></li>
        </ul>
        <%= link_to("Destroy Spot", "/spots/#{@spot.id}", {method: 'delete', data: {confirm: "This one...really?"}}) %>  
      </div>
    </div>
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>
-->

app/views/spots/update.html.erb
<h1>Spots#update</h1>
<p>Find me in app/views/spots/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
      <div class="form-group">
        <label>Email</label>
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label>Password</label>
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group">
        <label>Confirm Password</label>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
      </div>
      <div class="form-group">
        <label>Bio</label>
        <%= f.text_field :about, class: "form-control", placeholder: "About" %>
        <small id="aboutHelp" class="form-text text-muted"></small>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.text_field :image, class: "form-control", placeholder: "Profile Pic URL" %>
        <small id="imageHelp" class="form-text text-muted"></small>
      </div>
      <%= f.submit "Update Profile", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>My Line</h1>
<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="http://a.espncdn.com/combiner/i?img=/photo/2015/0909/as_nycskate01_2048.jpg&w=1024" alt ="skate">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://image.redbull.com/rbcom/010/2014-03-18/1331640254834_2/0010/1/1600/1067/1/gee-and-rachel-atherthon-downhill-training-fuerteventura.jpg" alt="Mountain Bikers">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="https://az760333.vo.msecnd.net/-/media/property/destination-residences-snowmass/840x500-media-block-cropped/drsnowmass_location_treespowdersnowboard-crpd840x500.jpg?ts=a6a87a61-35fc-4134-82cd-8dc477b1841a" alt="Snowboarder">
    </div>
  </div>
</div>

<h3>What line will you take?</h3>

app/views/users/new.html.erb
<h1>New You</h1>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
      <div class="form-group">
        <label>Email</label>
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label>Password</label>
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group">
        <label>Confirm Password</label>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
      </div>
      <div class="form-group">
        <label>Bio</label>
        <%= f.text_field :about, class: "form-control", placeholder: "About" %>
        <small id="aboutHelp" class="form-text text-muted"></small>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.text_field :image, class: "form-control", placeholder: "Profile Pic URL" %>
        <small id="imageHelp" class="form-text text-muted"></small>
      </div>
      <%= f.submit "Create Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<!--
<%= form_for(@user) do |f| %>
    <%= f.text_field(:name, {placeholder: "Name"}) %>
    <%= f.text_field(:email, {placeholder: "Email"}) %>
    <%= f.password_field(:password, {placeholder: "Password"}) %>
    <%= f.text_field(:image, {placeholder: "Profile Picture"}) %>
    <%= f.text_field(:about, {placeholder: "Bio"}) %>    
    <%= f.submit("New Ripper") %>
<% end %>
-->

app/views/users/show.html.erb
<header class = "header">
    <div class = "profile_img">
        <%= image_tag(@user.image) %>
    </div>
    <h1> <%= @user.name %> </h1>
    <p class = "bio"><%= @user.about %></p>
</header>
<div class="container">

<h2>Spots</h2>
    <% if @user == current_user %>
        <%= link_to "Add New Spot", new_spot_path %>
    <% end %>

<div class="card-deck">
<% @user.spots.each do |s| %>
  <div class="card">
    <img class="card-img-top" src=<%=s.image %> alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%=s.location%></h5>
      <p class="card-text"><%= s.description %></p>
      <ul class="card-text">
        <li><%= s.obstacles %></li>
        <li><%= s.level_of_difficulty %></li>
      </ul>
    </div>
    <div class="card-footer">
      <small class="text-muted"><%= link_to("Edit Spot", "/spots/#{s.id}/edit") %></small>
      <div>
        <small class="text-muted"><%= link_to("Destroy Spot", "/spots/#{s.id}", {method: 'delete', data: {confirm: "This one...really?"}}) %></small>
      </div>
    </div>  
  </div>
  <% end %>
</div>


<footer class = "container">
    <div class = "destroy">
        <%= link_to("Destroy User", "/users/#{@user.id}", {method: 'delete', data: {confirm: "This one...really?"}}) %>
    </div>
</footer>

</div>
<!--
<div class = "card-deck">
    <% @user.spots.each do |s| %>
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src=<%= s.image %> alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><%=s.location%></h5>
                <p class="card-text"><%= s.description %></p>
                <ul class="card-text">
                    <li><%= s.obstacles %></li>
                    <li><%= s.level_of_difficulty %></li>
                </ul>
                <div>
                    <%= link_to("Edit Spot", "/spots/#{s.id}/edit") %>  
                </div>
                <%= link_to("Destroy Spot", "/spots/#{s.id}", {method: 'delete', data: {confirm: "This one...really?"}}) %>    
            </div>
        </div>
    <% end %>
</div>     
</div>
-->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>